name: Deploy .NET Web API to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./WebPolizas/Webpolizas/Webpolizas.csproj

    - name: Build
      run: dotnet build ./WebPolizas/Webpolizas/Webpolizas.csproj --configuration Release

    - name: Publish
      run: dotnet publish ./WebPolizas/Webpolizas/Webpolizas.csproj -c Release -o publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: webapi-pruebas-hj   # Reemplaza con el nombre exacto de tu App Service en Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish_output
